language: node_js
node_js:
  - '12.13'
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: test
      name: 'Unit Tests'
      script: 'yarn run test'
    - stage: deploy
      script: 'yarn run build'
      name: 'Deploy to NPM'
      deploy:
        provider: script
        before_script:
        - yarn install
        script:
          - npx semantic-release
        email: $NPM_EMAIL_ADDRESS
        api_key: $NPM_AUTH_TOKEN
        cleanup: true
        on:
          all_branches: true
